apiVersion: v1
kind: Service
metadata:
  name: dummy-request-counter
spec:
  selector:
    app: dummy-request-counter
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    nodePort: 30080  # Optional: specify port (30000-32767 range)
  type: NodePort