apiVersion: v1
kind: Service
metadata:
  name: counter
spec:
  type: NodePort
  selector: { app: counter }
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 32080   # NodePort must be in 30000-32767
