apiVersion: apps/v1
kind: Deployment
metadata:
  name: requests-counter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: requests-counter
  template:
    metadata:
      labels:
        app: requests-counter
    spec:
      volumes:
        - name: logs
          emptyDir: {}
      containers:
        - name: app
          image: requests-counter:1.0.2
          imagePullPolicy: Never
          env:
            - name: REDIS_HOST
              value: "redis"
          ports:
            - containerPort: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: logs
              mountPath: /logs
        - name: log-sidecar
          image: busybox:1.36
          command: ["sh","-c","touch /logs/access.log; tail -n+1 -F /logs/access.log"]
          volumeMounts:
            - name: logs
              mountPath: /logs
