apiVersion: v1
kind: Service
metadata:
  name: requests-counter-svc
spec:
  selector:
    app: requests-counter
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
